export const wishlistCopy = {
  title: "Lista de presentes",
  speaker: "Thiago",
  lineEmpty: "Ainda não tem item. Coloca o primeiro comigo.",
  lineFresh:
    "Oi! Sou o Thiago. Montei essa lista. Escolhe um item, vê o valor, marca o seu nome.",
  lineProgress: "A missão andou. Ainda tem item livre, se você quiser entrar.",
  lineDone: "Fechou! Todos os itens já têm alguém.",
  quest: "Missão",
  subtitle: "Escolhe um item, vê o valor e abre a loja.",
  add: "Novo item",
  addTalk: "Me passa o nome, o valor, o link da loja e o link da foto.",
  reserveTalk: "Escreve seu nome pra ficar com esse item.",
  reservedTalk: "Esse item já tem dono.",
  reservedByYou: "Você ficou com esse item.",
  confirm: "Confirmar",
  save: "Salvar",
  back: "Voltar",
  release: "Liberar",
  saving: "Salvando...",
  viewProduct: "Ir pra loja",
  reserve: "Quero",
  reserved: "Reservado",
  seeReservation: "Ver",
  empty: "Nenhum item ainda. Coloca o primeiro.",
  loadError: "Não foi possível carregar a lista.",
  retry: "Tentar de novo",
}
