export const wishlistCopy = {
  title: "Lista de presentes",
  speaker: "Thiago",
  lineEmpty: "Ainda não tem item.",
  lineFresh:
    "Oi! Sou o Thiago. Montei essa lista. Escolhe um item, vê o valor, marca o seu nome.",
  lineProgress: "A missão andou. Ainda tem item livre, se você quiser entrar.",
  lineDone: "Fechou! Todos os itens já têm alguém.",
  quest: "Missão",
  subtitle: "Escolhe um item, vê o valor e abre a loja.",
  reserveTalk: "Escreve seu nome pra ficar com esse item.",
  reservedTalk: "Esse item já tem dono.",
  reservedByYou: "Você ficou com esse item.",
  confirm: "Confirmar",
  back: "Voltar",
  release: "Liberar",
  saving: "Salvando...",
  viewProduct: "Ir pra loja",
  reserve: "Quero",
  reserved: "Reservado",
  seeReservation: "Ver",
  empty: "Nenhum item ainda.",
  loadError: "Não foi possível carregar a lista.",
  retry: "Tentar de novo",
}
